// Generated by CoffeeScript 1.9.2
(function() {
  var multiples, num;

  multiples = (function() {
    var i, results;
    results = [];
    for (num = i = 0; i <= 10; num = ++i) {
      results.push(num * 10);
    }
    return results;
  })();

}).call(this);
